devices:
  iPhone 5s:
    [7.1, 8.0]

  iPhone 5:
    [7.1, 8.0]

  iPhone 6:
    [8.0]

  iPhone 6 Plus:
    [8.0]
default:
  os: iPhone 5s
  version: 8.1
  test_timeout: 120

build_configuration: 'Debug'