# remove either the iOS or Android depending on which project you are building.
# iOS Example
devices:
  iPhone 6:
    [8.3]

  iPhone 5s:
    [7.1, 8.3]

  iPhone 4s:
    [7.1, 8.3]

  iPhone 5:
    [7.1, 8.3]

  iPhone 6 Plus:
    [8.3]

default:
  os: iPhone 6
  version: 8.3
  test_timeout: 120

platform: 'iOS'
build_configuration: 'Debug'
app_name: 'MyApp'

# Android Example
devices:
  emulators:
    [bdd-sim]

default:
  os: Android
  version: Android
  test_timeout: 120

platform: 'Android'
build_configuration: 'local-Defaulttheme-Debug'
